services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=bitpin_project.settings
    depends_on:
      - db
      - redis
    entrypoint: ["/app/entrypoint.sh"]
    command: gunicorn bitpin_project.wsgi:application --bind 0.0.0.0:8000 --workers 3

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A bitpin_project worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=bitpin_project.settings
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A bitpin_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=bitpin_project.settings
    depends_on:
      - db
      - redis

volumes:
  postgres_data: